### ISSUE TITLE
Paraphase determines output prefix from input filename

### ISSUE THREAD

**Issue by williamrowell** [PacificBiosciences/paraphase#17]
If the sample name isn't sanitized in the expected way (e.g., contains a `.`), the output names may be non-unique.  For setting the prefix, I recommend determining the sample name from the read group headers instead of the filename, and providing a `--prefix` flag for intentional override.

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/issues/113

**Comment by xiao-chen-xc** [comment]
This is fixed in v3.1.1
