### ISSUE TITLE
test files

### ISSUE THREAD

**Issue by MagdalenaZZ** [PacificBiosciences/paraphase#22]
Hi - thanks for a great software!
I'm trying to write a unit test, and I've borrowed your test files for smn1 HG00733_smn1_realigned.bam
However, I cannot seem to run a test of paraphase without providing the whole genome, e.g. grch38 with flag --genome 38

Is there a way to make test files, so I can write a test with both a mini-bam and a mini-genome? 

Thanks!

**Comment by xiao-chen-xc** [comment]
Hi @MagdalenaZZ the minibam would work, but you would at least need to specify a fasta file with the full sequence of the chromosome that your gene of interest is on. For example, if you use the test smn1 bam file, you would need to run paraphase with `-r chr5.fa -g smn1`.

**Comment by MagdalenaZZ** [comment]
Thank you so much, I'll give that a go. It is a lot better with just one chromosome than the whole genome.
