### ISSUE TITLE
distinguishing reads for each paralog

### ISSUE THREAD

**Issue by indapa** [PacificBiosciences/paraphase#23]
This is not really a software issue, but a general question about the paraphrase algorithm. If it is aligning reads to one member of the gene family, how can it distinguish if a read is from a gene or its paralog? I know in the [paper](https://doi.org/10.1016/j.ajhg.2023.01.001) for SMN1/SMN2 it says:

> Paraphase extracts HiFi reads aligned to either SMN1 or SMN2 and realigns them to the SMN1 region. It then identifies variant positions throughout the 44 kb long region of interest (chr5: 70,917,100–70,961,220, GRCh38), which includes the SMN1 gene body plus upstream/downstream regions. Paraphase then assembles haplotypes by linking the phases of each variant site ([Figure 1](https://www.cell.com/ajhg/fulltext/S0002-9297(23)00001-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0002929723000010%3Fshowall%3Dtrue#gr1)). Haplotypes are assigned to SMN1 or SMN2 based on the sequence at the c.840 site, i.e., C is SMN1 and T is SMN2.

Is this the same for the other genes Paraphrase can analyze (like PMS1/PMS2)  Is there a known list of positions that are different between a gene and it's paralog to assist in haplotype assignment? 

Also, are their example BAM files I can use to play with the software? I don't have data of my own, but am trying to get more familiar with this application of long read sequencing.

**Comment by xiao-chen-xc** [comment]
Hi @indapa, Paraphase assembles reads into haplotypes (gene copies that are usually the length of the full gene plus flanking reigons) first, and then assigns haplotypes into genes or paralogs if there is prior information on how to differentiate the genes. The gene differentiation is implemented currently for genes like PMS2, NCF1, SMN1, IKBKG, STRC, OPN1LW, HBA1/2 etc. We can add any genes you are interested in. Also, feel free to check out our new [preprint](https://www.biorxiv.org/content/10.1101/2024.04.19.590294) for more information. 

For example BAMs, you can try HPRC data. See https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0

**Comment by indapa** [comment]
Great, very helpful information. I'll checkout the new preprint and look at the example BAMs. Thank you for very much for taking the time to respond.
