### ISSUE TITLE
Question about multi-threading

### ISSUE THREAD

**Issue by gabeng** [PacificBiosciences/paraphase#25]
Hi,

I am wondering how to use the multi-threading option. Using this command, paraphase only seems to run on a single core. What dies the `-t` parameter actually control?

```
paraphase \
        -t 31 \
        -p sample \
        --genome 38 \
        -o . \
        -r GRCh38.fa \
        -b sample.bam
```

**Comment by xiao-chen-xc** [comment]
Hi @gabeng in your case you would request 31 cores - all the Paraphase-targeted regions will be divided into 31 groups, each of which is analyzed by one core. This should be much faster than using a single core.

**Comment by xiao-chen-xc** [comment]
Yes I think more work is needed to optimize Paraphase for targeted data. We are working on some improvements and hopefully they will be included in the next release.
