### ISSUE TITLE
Run paraphase on CHM13 reference

### ISSUE THREAD

**Issue by EddieLee08** [PacificBiosciences/paraphase#28]
Hi Xiao；

Thanks for this great tool！

I wonder if _paraphase_ could support T2T-CHM13 as reference genome. I've tried to set` -r /path/to/chm13.fa` but it seems not working well, is there any technical bottleneck?

Many thanks！

**Comment by xiao-chen-xc** [comment]
Hi @EddieLee08 CHM13 is not supported at the moment. It would require a new config file that defines the segmental duplication regions to analyze. We have plans to add it in the future.

**Comment by EddieLee08** [comment]
Thank a lot for your speedy reply! I'm awaiting the updates with great expection.
